### ISSUE TITLE
Issue running ParseCNV , where it says  cannot find any probe from the map file.

### ISSUE THREAD

**Issue by ChitrArpita** [CAG-CNV/ParseCNV2#1]
**command** : perl ./ParseCNVRelease_21/ParseCNV.pl ALL_report_cated_CASE.goodcnv ALL_report_cated_CONTROL.goodcnv Cases_myData.fam ChrSnp0Pos_mydata.map --build hg19
**output on screen** : ## 
awk '{print $5}' ALL_report_cated_CASE.goodcnv | uniq | sed 's/^/0\t/' | sed 's/$/\t0\t0\t0\t2/' > ALL_report_cated_CASE.goodcnv.fam
/usr/bin/bash
/packages/modules/interpreters/R-3.5.1/bin/R
which: no plink in (/packages/modules/gistic:/packages/modules/interpreters/R-3.5.1/bin:/packages/modules/bio/delly/src:/opt/openmpi/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/ganglia/bin:/opt/ganglia/sbin:/usr/lpp/mmfs/bin:/opt/ibutils/bin:/opt/pdsh/bin:/opt/rocks/bin:/opt/rocks/sbin:/opt/gridengine/bin/lx-amd64)
Running Command: perl ./ParseCNVRelease_21/ParseCNV.pl ALL_report_cated_CASE.goodcnv ALL_report_cated_CONTROL.goodcnv Cases_myData.fam ChrSnp0Pos_mydata.map --build hg19
My Path ./ParseCNVRelease_21/
Unable to connect to web to check latest version
Run Started 04:16:03 PM on May 23 2022
Chromosomes found: chr1 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr2 chr20 chr21 chr22 chr3 chr4 chr5 chr6 chr7 chr8 chr9 
WARNING: 93363 probes were found in rawcnv but not in map. These will be automatically defined as in temp/MissingSNPs.txt
If certain full snp set is in map and receive error <Missing Probe in Rawcnv file but not Map file!> then there are likely incorrect fields in .rawcnv. See .rawcnv lines in temp/MissingSNPs_FullLines.txt. Search for these lines in your .rawcnv file, delete them, and run again.
Average Inter Probe Distance: 29834.015
Number of Probes:93363
Done Initialization
Progress:100%
Results
-------
Cases:      1148
Unaffected: 0
Controls:   0
Count Significant Deletion Probes Case Enrich:       0
Count Significant Duplication Probes Case Enrich:    0
Count Significant Deletion Probes Control Enrich:    0
Count Significant Duplication Probes Control Enrich: 0
GIFDel:0.000
GIFDup:0.000

**Comment by joeglessner1** [comment]
Thanks for your interest in ParseCNV.
The only way to see this output message you have is through ParseCNV determining the command as "Advanced Usage" where only 1 rawcnv file is provided after the ParseCNV.pl, instead of the classic: Cases.rawcnv Controls.rawcnv Cases.fam ChrSnp0Pos.map:
awk '{print $5}' ALL_report_cated_CASE.goodcnv | uniq | sed 's/^/0\t/' | sed 's/$/\t0\t0\t0\t2/' > ALL_report_cated_CASE.goodcnv.fam

That is the first indication, then only Cases count exists which supports this idea.
Cases: 1148
Unaffected: 0
Controls: 0

Please check to make sure that only single spaces delimit each part of the command, without any stray non-printable characters like carriage returns or text encoding issues.
I suggest trying copying each part of the command, paste, and manually hit space.
Another less manual suggestion is to run this non-printable character removal command:
sed 's/\r//' ChitrArpita_ParseCNV_Command.sh | grep -v ^$ | tr -cd '[:print:]^[\n,\t]' > ChitrArpita_ParseCNV_Command_Cleaned.sh
Then try running that version.

**Comment by joeglessner1** [comment]
No reply, closing.
