### ISSUE TITLE
Does input require snp info?

### ISSUE THREAD

**Issue by sophie-03** [CAG-CNV/ParseCNV2#5]
Hello, I have a question regarding the input required for ParseCNV2.  

Do I need to have the number of snps, and start/end snp information in order to run a CNV-association test? 

For example, could I do an association test for CNVs that I only have the following information for: cnv location, copy number, individual ID? If so, can I leave those columns in the input blank or fill with an arbitrary value? Does having this information missing affect how the output is interpreted? 

Thanks in advance.

**Comment by joeglessner1** [comment]
No, you do not need to have the number of snps, and start/end snp information in order to run a CNV-association test with ParseCNV2. The number of SNPs would be checked as a "RedFlag" if provided, but not necessary. Older versions of original ParseCNV did require start/end snp information but I switched to Chr:Position based marker information.
